language: node_js
node_js:
  - 12.16.3
addons:
  chrome: stable
before_script:
      - npm install -g @angular/cli
branches:
    only:
        - master
        - /^release-.*$/
        - /^bugfix-.*$/
script:
  - ng lint
  - ng build
  - ng test
  - echo "$TRAVIS_BRANCH"
  - if [[ "$TRAVIS_BRANCH" == "master" || $TRAVIS_BRANCH =~ "^release-.*$" ]]; then echo "$DOCKER_PW" | docker login --username $DOCKER_USER --password-stdin; docker build -f Dockerfile -t $DOCKER_USER/foodstore:latest ./; GIT_SHA="$(git rev-parse --short HEAD)"; docker tag $DOCKER_USER/foodstore:latest $DOCKER_USER/foodstore:$GIT_SHA; docker push $DOCKER_USER/foodstore:latest; docker push $DOCKER_USER/foodstore:$GIT_SHA;
    else
      echo "DOCKER NOT REQUIRED FOR BRANCH";
    fi
