language: node_js
node_js:
  - 12.16.3
addons:
  chrome: stable
before_script:
      - npm install -g @angular/cli
script:
  - ng lint
  - ng build
  - ng test
#  - echo "$DOCKER_PW" | docker login --username $DOCKER_USER --password-stdin
#  - docker build -f Dockerfile -t $DOCKER_USER/foodstore:latest ./
#  - GIT_SHA="$(git rev-parse --short HEAD)"
#  - docker tag $DOCKER_USER/foodstore:latest $DOCKER_USER/demo:$GIT_SHA
#  - docker push $DOCKER_USER/foodstore:latest
#  - docker push $DOCKER_USER/foodstore:$GIT_SHA
