language: node_js
node_js:
  - 12.16.3
addons:
  chrome: stable
before_script:
      - npm install -g @angular/cli
branches:
    only:
        - master
        - /^release-.*$/
        - /^bugfix-.*$/
script:
#  - ng lint NO TEST TILL SCRIPT WORKS AS EXPECTED!
#  - ng build
#  - ng test
#  - if: branch == master || branch == /^release-.*$/
  if branch = master
      - echo "$DOCKER_PW" | docker login --username $DOCKER_USER --password-stdin
      - docker build -f Dockerfile -t $DOCKER_USER/foodstore:latest ./
      - GIT_SHA="$(git rev-parse --short HEAD)"
      - docker tag $DOCKER_USER/foodstore:latest $DOCKER_USER/foodstore:$GIT_SHA
      - docker push $DOCKER_USER/foodstore:latest
      - docker push $DOCKER_USER/foodstore:$GIT_SHA
